use_frameworks!
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'http://10.18.207.188/iOSModules/iOS_SpecsRepository'

target 'JHKVideoPlayer_Example' do
  pod 'JHKVideoPlayer', :path => ‘../JHKVideoPlayer.podspec’
#  pod 'iOS_Networking_CPN'

  target 'JHKVideoPlayer_Tests' do
    inherit! :search_paths
    
  end
end
